### ISSUE TITLE
Error details not updating as user types

### ISSUE THREAD

**Issue by moniuch** [ngspot/ngx-errors#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I just downloaded 3.2.0, which successfully solves #9.

_Although I can't resist the feeling that there is another problem. The html templates don't update with `ngxErrors` immediately, sometimes I need to make several changes and saves before the `ngxErrors` html kicks in. Will have to try to reproduce it on Stackblitz before I am sure this is not my setup_
 
The problem I am facing is that the syntax for displaying error details 

```html
  <div ngxErrors="password">
    <div ngxError="passwordLength" #myMin="ngxError">
      Password has to be at least {{myMin.err.min}} characters long.
      Only {{myMin.err.actual}} typed
    </div>
  </div>
```

doesn't seem to update as I am typing.

![image 2022-02-04 12-12-15](https://user-images.githubusercontent.com/681956/152519536-6506cf7b-bb09-421f-9a55-397fb2d5a83d.png)

This is a reactive form:

```ts
this.fb.group({
  password: ['', [passwordLengthValidator()]],
});
```

This is my custom validator:

```ts
export const passwordLengthValidator = (min = 16): ValidatorFn =>
  (c: AbstractControl) => {
    console.log('validating', c.value)
    if(c.value.trim() === ''){
      return null
    }

    const actualLen = c.value.length;
    return actualLen >= min
      ? null
      : { passwordLength: { min, actual: actualLen }};
}
```

Am I doing anything wrong? (`changeDetection` left at default.)

## Minimal reproduction of the problem with instructions

Will provide stackblitz later if successful.

## Environment

<pre><code>
Angular version: 13.1.2
ngx-errors: 3.2.0
nx workspace
lazy loaded module
reactive form

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DmitryEfimenko** [comment]
feel free to comment if you can come up with a repro
