### ISSUE TITLE
Update tslib peer dependency to support 2.x versions (Angular v12)

### ISSUE THREAD

**Issue by Chris2fourlaw** [ngspot/ngx-errors#21]
Hey Dmitry,

Can you update this to support version 2.4.0 of tslib?

Thanks!

**Comment by DmitryEfimenko** [comment]
I'm investigating the need to have it as a dependency at all. I'll see if it can be removed first

**Comment by DmitryEfimenko** [comment]
it appears that Angular [recommends keeping tslib](https://angular.io/guide/angular-package-format#tslib) as a direct dependency for Angular libraries. Furthemore, the [suggested version](https://angular.io/guide/migration-update-libraries-tslib) today is "^2.0.0". That's what is [specified in the package.json](https://github.com/ngspot/ngx-errors/blob/master/projects/ngx-errors/package.json#L27) file of ngx-errors as well. Notice the carrot: `^` in the version. It means that any 2.x.x version is acceptable - including the requested 2.4.0.

Was there a particular reason for the request?

**Comment by Chris2fourlaw** [comment]
I get the error: 

`npm WARN @ngspot/ngx-errors@2.0.2 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.`

when I use `"tslib": "^2.4.0",`

**Comment by Chris2fourlaw** [comment]
Oh dang this may be because I'm using `"@ngspot/ngx-errors": "^2.0.2",`

**Comment by DmitryEfimenko** [comment]
Cool, please try upgrading and let me know if still have issues
