### ISSUE TITLE
What is plan for Migrating to Angular 15 .Will this current version support Angular 15?

### ISSUE THREAD

**Issue by Ranga-RV6464** [ngspot/ngx-errors#22]
## I'm submitting a new feature request to support Angular v14 and v15

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently supporting  Angular versions till 13  

## Expected behavior

Need to support Angular 14 and 15 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DmitryEfimenko** [comment]
The library is compiled using ng v13. The "requirement" of ng v13 is just a number specified [here](https://github.com/ngspot/ngx-errors/blob/master/projects/ngx-errors/package.json#L6). The library should work already with Angular 14. It may give you a warning during installation, but you can force install and it should still work. We can adjust that version number to include 14 to get rid of warnings.

Let me know if you are getting some other errors when using this library with Angular 14.

**Comment by Ranga-RV6464** [comment]
The current version is not giving any issues with Angular v14. It would be nice to have the Angular Version adjusted to 14 in this project .
